### ISSUE TITLE
Support list of names in the parser to match profiles by name

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-sortinghat#198]
In the same way SortingHat supports a list of emails when parsing an identities file using GrimoireLab format, SH should also support this file including a list of names or aliases. Having this list would allow to match profiles using different names. After including this change, the YAML file could contain an entry like this one:

```
- profile:
    name: Tom Marvolo Riddle
  alias:
    - Tom M. Riddle
    - Tom Riddle
  enrollments:
    - organization: Dark Arts, Inc.
  email:
    - tom.riddle@dark.org
    - tommriddle@users.noreply.github.com
```
