### ISSUE TITLE
Last enrollment is missing using `load --identities`

### ISSUE THREAD

**Issue by zhquan** [chaoss/grimoirelab-sortinghat#588]
I am missing the last enrollment when I load an identities file using `load --identities` when the start date is the same as the last end date and the organization is also the same.

Example:

identities.yml
```
- profile:
    name: Quan Zhou
  enrollments:
    - organization: Bitergia
      start: 2015-01-01
      end: 2015-07-01
    - organization: Bitergia
      start: 2015-07-05
      end: 2020-01-01
    - organization: Bitergia
      start: 2020-01-01
```
Create a new database
```
$ sortinghat --host localhost -u root init test_sh
```
Use `grimoirelab2sh` to convert identities.yml to identities.json
```
$ grimoirelab2sh -i identities.yml -s manual -o identities.json --no-email-validation --no-enrollment-periods-validation
```
Load identities.json
```
$ sortinghat --host localhost -u root --database test_sh load --identities identities.json
```
Check the result
```
$ sortinghat --host localhost -u root --database test_sh show --term quan

Profile:
    * Name: Quan Zhou
    * E-Mail: -
    * Gender: -
    * Bot: No
    * Country: -

Identities:
  87d16e4f10ed9d8372ea55cdcc6b55e78547acd6	Quan Zhou	-	-	manual

Enrollments:
  Bitergia	2015-01-01 00:00:00	2015-07-01 00:00:00
  Bitergia	2015-07-05 00:00:00	2020-01-01 00:00:00
```
It should be 
```
Profile:
    * Name: Quan Zhou
    * E-Mail: -
    * Gender: -
    * Bot: No
    * Country: -

Identities:
  87d16e4f10ed9d8372ea55cdcc6b55e78547acd6	Quan Zhou	-	-	manual

Enrollments:
  Bitergia	2015-01-01 00:00:00	2015-07-01 00:00:00
  Bitergia	2015-07-05 00:00:00	2020-01-01 00:00:00
  Bitergia	2020-01-01 00:00:00	2100-01-01 00:00:00
```
